### PR TITLE
Update MembershipType.php

### PR DESCRIPTION
**Pull request by KarinG**
http://forum.civicrm.org/index.php/topic,30672.0.html

### CODE REVIEW

**Comment by nganivet** [comment]
Karin - I have noticed this patch is not included in the latest version of CiviCRM (https://github.com/civicrm/civicrm-core/blob/master/CRM/Member/BAO/MembershipType.php). We try to only back-port fixes in LTS, rather than develop new functions or modify behaviors independently of the core team.

Could you please file a bug in JIRA (http://issues.civicrm.org) with this patch attached, and tell us when it is accepted by the core team so we can then merge it back in LTS.

Thanks.

**Comment by KarinG** [comment]
Sorry - meant to do that at the same time but got distracted. I've now opened an issue in JIRA:
http://issues.civicrm.org/jira/browse/CRM-13786

**Comment by nganivet** [comment]
Thanks Karin, will merge as soon as accepted by core.

Sent from my iPhone

On Nov 17, 2013, at 8:03 AM, Karin Gerritsen notifications@github.com
wrote:

Sorry - meant to do that at the same time but got distracted. I've now
opened an issue in JIRA:
http://issues.civicrm.org/jira/browse/CRM-13786

—
Reply to this email directly or view it on
GitHubhttps://github.com/CiviCRM42/civicrm42-core/pull/54#issuecomment-28649985
.

**Comment by davecivicrm** [comment]
I've created  a PR for 4.4 branch based on this PR + change noted by Karin here:
http://issues.civicrm.org/jira/browse/CRM-13786?focusedCommentId=54287&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-54287

The 4.4 PR is https://github.com/civicrm/civicrm-core/pull/2028

**Comment by eileenmcnaughton** [comment]
I am pretty sure the PR in core changed after dgg's comments above

**Comment by nganivet** [comment]
Eileen – I am packaging 4.2.14 now. Should I include this PR even though it breaks some tests (ie. is the patch wrong or should the tests be updated)?

Nicolas Ganivet | Principal | nicolas@cividesk.com
cividesk | +1 (866) 670-7165 | www.cividesk.com

**Comment by davecivicrm** [comment]
I tested the new 4.3 PR against the api tests which had broken previously and they passed.
https://github.com/civicrm/civicrm-core/pull/2060

**Comment by nganivet** [comment]
Dave – seems lobo also corrected stuff after your commit. Should I merge these 2 commits in 4.2 LTS or just yours?

Nicolas Ganivet | Principal | nicolas@cividesk.com
cividesk | +1 (866) 670-7165 | www.cividesk.com

**Comment by eileenmcnaughton** [comment]
Nicholas - I would skip this PR if you are not sure about it & just do the release

**Comment by KarinG** [comment]
The new civicrm/civicrm-core#2060 contains it all (I just double checked):
https://github.com/davecivicrm/civicrm-core/commit/82bee9d59851192be6dc544915566a6536b271fe
It fixes both the endDate issue as well as a startDate issue (issue we came upon while fixing the endDate one).

**Comment by nganivet** [comment]
I have just created a clean PR based on Dave's code and merged. So closing this one as now redundant.
Thanks Karin for this patch and giving me the pointer to Dave's final code.

**Pull request closed without merging**
