### PR TITLE
CRM-13550 previous didn't deal with empty very well

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
(these commits are all a bit of a pig's ear because I was rushing it & didn't want to have to run tests locally)

### CODE REVIEW

**Comment by nganivet** [comment]
Yes, we noticed … love the expression a bit of a pig’s ear!
Thanks for bringing these changes in, should improve security with remote calls.

**Comment by eileenmcnaughton** [comment]
I can't get away with anything can I?

**Comment by eileenmcnaughton** [comment]
Argh - sill not right - I can't get the tests to run locally @ the moment :-( This time I can see there is a needle/haystack problem

**Comment by eileenmcnaughton** [comment]
phew finally we are BLUE again!!! https://test.civicrm.org/

**Pull request merged**
